### ISSUE TITLE
Mulit server environment

### ISSUE THREAD

**Issue by kansi** [ianwalter/bouncer#18]
Hi,
It is stated in README file that bouncer can be used in a multi-server environment which (if I understand correctly) will be done by clustering redis (right ?). But when I track the [code](https://github.com/ianwalter/bouncer/blob/master/lib/bouncer/plugs/authorize.ex#L20) for session verfication [here](https://github.com/ianwalter/bouncer/blob/master/lib/bouncer/token.ex#L45), I see that `Token.verify/3` exposed by Phoenix is used to verify the token. Since I don't see how Phoenix will propagate tokens I have concluded that if session validation request hits any other server different from the one it was created on `Token.verify/3` would return saying invalid token.

Could please elaborate how is it supposed to work in a multi-server environment ?

**Comment by ianwalter** [comment]
Yes, but you don't necessarily need a Redis cluster for that. You can have multiple application servers as long as they're connected to the same Redis instance **or** cluster. 

`Token.verify/3` simply validates that the given token has been generated with the same salt (Bouncer uses "user" for session tokens, "password" for password reset tokens, etc.) and secret_key_base which is specified in your applications config so I think your conclusion is incorrect but if you want to create a proof I'd be happy to take a look at it.

There isn't anything special you have to do to make it work in a muti-server environment although I guess if you're trying to use Bouncer to manage sessions for 2 different applications then I would make sure the secret_key_base is the same for both of them.
